/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTeacherRouteRouteImport } from './routes/_authenticated/teacher/route'
import { Route as AuthenticatedSpecialistRouteRouteImport } from './routes/_authenticated/specialist/route'
import { Route as AuthenticatedParentRouteRouteImport } from './routes/_authenticated/parent/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedSpecialistIndexRouteImport } from './routes/_authenticated/specialist/index'
import { Route as AuthenticatedParentIndexRouteImport } from './routes/_authenticated/parent/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTeacherNotesRouteImport } from './routes/_authenticated/teacher/notes'
import { Route as AuthenticatedTeacherMessagesRouteImport } from './routes/_authenticated/teacher/messages'
import { Route as AuthenticatedTeacherGradesRouteImport } from './routes/_authenticated/teacher/grades'
import { Route as AuthenticatedTeacherChildrenRouteImport } from './routes/_authenticated/teacher/children'
import { Route as AuthenticatedTeacherAttendanceRouteImport } from './routes/_authenticated/teacher/attendance'
import { Route as AuthenticatedTeacherAssignmentsRouteImport } from './routes/_authenticated/teacher/assignments'
import { Route as AuthenticatedSpecialistPlansRouteImport } from './routes/_authenticated/specialist/plans'
import { Route as AuthenticatedSpecialistNotesRouteImport } from './routes/_authenticated/specialist/notes'
import { Route as AuthenticatedSpecialistMessagesRouteImport } from './routes/_authenticated/specialist/messages'
import { Route as AuthenticatedSpecialistEvaluationsRouteImport } from './routes/_authenticated/specialist/evaluations'
import { Route as AuthenticatedSpecialistDiagnosesRouteImport } from './routes/_authenticated/specialist/diagnoses'
import { Route as AuthenticatedSpecialistChildrenRouteImport } from './routes/_authenticated/specialist/children'
import { Route as AuthenticatedSpecialistAppointmentsRouteImport } from './routes/_authenticated/specialist/appointments'
import { Route as AuthenticatedParentProgressRouteImport } from './routes/_authenticated/parent/progress'
import { Route as AuthenticatedParentMessagesRouteImport } from './routes/_authenticated/parent/messages'
import { Route as AuthenticatedParentDiagnosisRouteImport } from './routes/_authenticated/parent/diagnosis'
import { Route as AuthenticatedParentChildrenRouteImport } from './routes/_authenticated/parent/children'
import { Route as AuthenticatedParentAttendanceRouteImport } from './routes/_authenticated/parent/attendance'
import { Route as AuthenticatedParentAssignmentsRouteImport } from './routes/_authenticated/parent/assignments'
import { Route as AuthenticatedParentAppointmentsRouteImport } from './routes/_authenticated/parent/appointments'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminStatisticsRouteImport } from './routes/_authenticated/admin/statistics'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminChildrenRouteImport } from './routes/_authenticated/admin/children'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin/appointments'
import { Route as AuthenticatedAdminUserUserIdRouteImport } from './routes/_authenticated/admin/user.$userId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRouteRoute =
  AuthenticatedTeacherRouteRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpecialistRouteRoute =
  AuthenticatedSpecialistRouteRouteImport.update({
    id: '/specialist',
    path: '/specialist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParentRouteRoute =
  AuthenticatedParentRouteRouteImport.update({
    id: '/parent',
    path: '/parent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedSpecialistIndexRoute =
  AuthenticatedSpecialistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedParentIndexRoute =
  AuthenticatedParentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedTeacherNotesRoute =
  AuthenticatedTeacherNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherMessagesRoute =
  AuthenticatedTeacherMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherGradesRoute =
  AuthenticatedTeacherGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherChildrenRoute =
  AuthenticatedTeacherChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherAttendanceRoute =
  AuthenticatedTeacherAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherAssignmentsRoute =
  AuthenticatedTeacherAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedSpecialistPlansRoute =
  AuthenticatedSpecialistPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedSpecialistNotesRoute =
  AuthenticatedSpecialistNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedSpecialistMessagesRoute =
  AuthenticatedSpecialistMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedSpecialistEvaluationsRoute =
  AuthenticatedSpecialistEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedSpecialistDiagnosesRoute =
  AuthenticatedSpecialistDiagnosesRouteImport.update({
    id: '/diagnoses',
    path: '/diagnoses',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedSpecialistChildrenRoute =
  AuthenticatedSpecialistChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedSpecialistAppointmentsRoute =
  AuthenticatedSpecialistAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedSpecialistRouteRoute,
  } as any)
const AuthenticatedParentProgressRoute =
  AuthenticatedParentProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedParentMessagesRoute =
  AuthenticatedParentMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedParentDiagnosisRoute =
  AuthenticatedParentDiagnosisRouteImport.update({
    id: '/diagnosis',
    path: '/diagnosis',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedParentChildrenRoute =
  AuthenticatedParentChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedParentAttendanceRoute =
  AuthenticatedParentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedParentAssignmentsRoute =
  AuthenticatedParentAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedParentAppointmentsRoute =
  AuthenticatedParentAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedParentRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStatisticsRoute =
  AuthenticatedAdminStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminChildrenRoute =
  AuthenticatedAdminChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUserUserIdRoute =
  AuthenticatedAdminUserUserIdRouteImport.update({
    id: '/user/$userId',
    path: '/user/$userId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/parent': typeof AuthenticatedParentRouteRouteWithChildren
  '/specialist': typeof AuthenticatedSpecialistRouteRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/children': typeof AuthenticatedAdminChildrenRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/appointments': typeof AuthenticatedParentAppointmentsRoute
  '/parent/assignments': typeof AuthenticatedParentAssignmentsRoute
  '/parent/attendance': typeof AuthenticatedParentAttendanceRoute
  '/parent/children': typeof AuthenticatedParentChildrenRoute
  '/parent/diagnosis': typeof AuthenticatedParentDiagnosisRoute
  '/parent/messages': typeof AuthenticatedParentMessagesRoute
  '/parent/progress': typeof AuthenticatedParentProgressRoute
  '/specialist/appointments': typeof AuthenticatedSpecialistAppointmentsRoute
  '/specialist/children': typeof AuthenticatedSpecialistChildrenRoute
  '/specialist/diagnoses': typeof AuthenticatedSpecialistDiagnosesRoute
  '/specialist/evaluations': typeof AuthenticatedSpecialistEvaluationsRoute
  '/specialist/messages': typeof AuthenticatedSpecialistMessagesRoute
  '/specialist/notes': typeof AuthenticatedSpecialistNotesRoute
  '/specialist/plans': typeof AuthenticatedSpecialistPlansRoute
  '/teacher/assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher/children': typeof AuthenticatedTeacherChildrenRoute
  '/teacher/grades': typeof AuthenticatedTeacherGradesRoute
  '/teacher/messages': typeof AuthenticatedTeacherMessagesRoute
  '/teacher/notes': typeof AuthenticatedTeacherNotesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/parent/': typeof AuthenticatedParentIndexRoute
  '/specialist/': typeof AuthenticatedSpecialistIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/admin/user/$userId': typeof AuthenticatedAdminUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/children': typeof AuthenticatedAdminChildrenRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/parent/appointments': typeof AuthenticatedParentAppointmentsRoute
  '/parent/assignments': typeof AuthenticatedParentAssignmentsRoute
  '/parent/attendance': typeof AuthenticatedParentAttendanceRoute
  '/parent/children': typeof AuthenticatedParentChildrenRoute
  '/parent/diagnosis': typeof AuthenticatedParentDiagnosisRoute
  '/parent/messages': typeof AuthenticatedParentMessagesRoute
  '/parent/progress': typeof AuthenticatedParentProgressRoute
  '/specialist/appointments': typeof AuthenticatedSpecialistAppointmentsRoute
  '/specialist/children': typeof AuthenticatedSpecialistChildrenRoute
  '/specialist/diagnoses': typeof AuthenticatedSpecialistDiagnosesRoute
  '/specialist/evaluations': typeof AuthenticatedSpecialistEvaluationsRoute
  '/specialist/messages': typeof AuthenticatedSpecialistMessagesRoute
  '/specialist/notes': typeof AuthenticatedSpecialistNotesRoute
  '/specialist/plans': typeof AuthenticatedSpecialistPlansRoute
  '/teacher/assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher/children': typeof AuthenticatedTeacherChildrenRoute
  '/teacher/grades': typeof AuthenticatedTeacherGradesRoute
  '/teacher/messages': typeof AuthenticatedTeacherMessagesRoute
  '/teacher/notes': typeof AuthenticatedTeacherNotesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/parent': typeof AuthenticatedParentIndexRoute
  '/specialist': typeof AuthenticatedSpecialistIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/admin/user/$userId': typeof AuthenticatedAdminUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/parent': typeof AuthenticatedParentRouteRouteWithChildren
  '/_authenticated/specialist': typeof AuthenticatedSpecialistRouteRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/children': typeof AuthenticatedAdminChildrenRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/parent/appointments': typeof AuthenticatedParentAppointmentsRoute
  '/_authenticated/parent/assignments': typeof AuthenticatedParentAssignmentsRoute
  '/_authenticated/parent/attendance': typeof AuthenticatedParentAttendanceRoute
  '/_authenticated/parent/children': typeof AuthenticatedParentChildrenRoute
  '/_authenticated/parent/diagnosis': typeof AuthenticatedParentDiagnosisRoute
  '/_authenticated/parent/messages': typeof AuthenticatedParentMessagesRoute
  '/_authenticated/parent/progress': typeof AuthenticatedParentProgressRoute
  '/_authenticated/specialist/appointments': typeof AuthenticatedSpecialistAppointmentsRoute
  '/_authenticated/specialist/children': typeof AuthenticatedSpecialistChildrenRoute
  '/_authenticated/specialist/diagnoses': typeof AuthenticatedSpecialistDiagnosesRoute
  '/_authenticated/specialist/evaluations': typeof AuthenticatedSpecialistEvaluationsRoute
  '/_authenticated/specialist/messages': typeof AuthenticatedSpecialistMessagesRoute
  '/_authenticated/specialist/notes': typeof AuthenticatedSpecialistNotesRoute
  '/_authenticated/specialist/plans': typeof AuthenticatedSpecialistPlansRoute
  '/_authenticated/teacher/assignments': typeof AuthenticatedTeacherAssignmentsRoute
  '/_authenticated/teacher/attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/_authenticated/teacher/children': typeof AuthenticatedTeacherChildrenRoute
  '/_authenticated/teacher/grades': typeof AuthenticatedTeacherGradesRoute
  '/_authenticated/teacher/messages': typeof AuthenticatedTeacherMessagesRoute
  '/_authenticated/teacher/notes': typeof AuthenticatedTeacherNotesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/parent/': typeof AuthenticatedParentIndexRoute
  '/_authenticated/specialist/': typeof AuthenticatedSpecialistIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/admin/user/$userId': typeof AuthenticatedAdminUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/parent'
    | '/specialist'
    | '/teacher'
    | '/dashboard'
    | '/admin/appointments'
    | '/admin/children'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/statistics'
    | '/admin/users'
    | '/parent/appointments'
    | '/parent/assignments'
    | '/parent/attendance'
    | '/parent/children'
    | '/parent/diagnosis'
    | '/parent/messages'
    | '/parent/progress'
    | '/specialist/appointments'
    | '/specialist/children'
    | '/specialist/diagnoses'
    | '/specialist/evaluations'
    | '/specialist/messages'
    | '/specialist/notes'
    | '/specialist/plans'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/children'
    | '/teacher/grades'
    | '/teacher/messages'
    | '/teacher/notes'
    | '/admin/'
    | '/parent/'
    | '/specialist/'
    | '/teacher/'
    | '/admin/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/admin/appointments'
    | '/admin/children'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/statistics'
    | '/admin/users'
    | '/parent/appointments'
    | '/parent/assignments'
    | '/parent/attendance'
    | '/parent/children'
    | '/parent/diagnosis'
    | '/parent/messages'
    | '/parent/progress'
    | '/specialist/appointments'
    | '/specialist/children'
    | '/specialist/diagnoses'
    | '/specialist/evaluations'
    | '/specialist/messages'
    | '/specialist/notes'
    | '/specialist/plans'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/children'
    | '/teacher/grades'
    | '/teacher/messages'
    | '/teacher/notes'
    | '/admin'
    | '/parent'
    | '/specialist'
    | '/teacher'
    | '/admin/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/parent'
    | '/_authenticated/specialist'
    | '/_authenticated/teacher'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/children'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/statistics'
    | '/_authenticated/admin/users'
    | '/_authenticated/parent/appointments'
    | '/_authenticated/parent/assignments'
    | '/_authenticated/parent/attendance'
    | '/_authenticated/parent/children'
    | '/_authenticated/parent/diagnosis'
    | '/_authenticated/parent/messages'
    | '/_authenticated/parent/progress'
    | '/_authenticated/specialist/appointments'
    | '/_authenticated/specialist/children'
    | '/_authenticated/specialist/diagnoses'
    | '/_authenticated/specialist/evaluations'
    | '/_authenticated/specialist/messages'
    | '/_authenticated/specialist/notes'
    | '/_authenticated/specialist/plans'
    | '/_authenticated/teacher/assignments'
    | '/_authenticated/teacher/attendance'
    | '/_authenticated/teacher/children'
    | '/_authenticated/teacher/grades'
    | '/_authenticated/teacher/messages'
    | '/_authenticated/teacher/notes'
    | '/_authenticated/admin/'
    | '/_authenticated/parent/'
    | '/_authenticated/specialist/'
    | '/_authenticated/teacher/'
    | '/_authenticated/admin/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/specialist': {
      id: '/_authenticated/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof AuthenticatedSpecialistRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/specialist/': {
      id: '/_authenticated/specialist/'
      path: '/'
      fullPath: '/specialist/'
      preLoaderRoute: typeof AuthenticatedSpecialistIndexRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/parent/': {
      id: '/_authenticated/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthenticatedParentIndexRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/teacher/notes': {
      id: '/_authenticated/teacher/notes'
      path: '/notes'
      fullPath: '/teacher/notes'
      preLoaderRoute: typeof AuthenticatedTeacherNotesRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/messages': {
      id: '/_authenticated/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof AuthenticatedTeacherMessagesRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/grades': {
      id: '/_authenticated/teacher/grades'
      path: '/grades'
      fullPath: '/teacher/grades'
      preLoaderRoute: typeof AuthenticatedTeacherGradesRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/children': {
      id: '/_authenticated/teacher/children'
      path: '/children'
      fullPath: '/teacher/children'
      preLoaderRoute: typeof AuthenticatedTeacherChildrenRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/attendance': {
      id: '/_authenticated/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof AuthenticatedTeacherAttendanceRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/assignments': {
      id: '/_authenticated/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof AuthenticatedTeacherAssignmentsRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/specialist/plans': {
      id: '/_authenticated/specialist/plans'
      path: '/plans'
      fullPath: '/specialist/plans'
      preLoaderRoute: typeof AuthenticatedSpecialistPlansRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/specialist/notes': {
      id: '/_authenticated/specialist/notes'
      path: '/notes'
      fullPath: '/specialist/notes'
      preLoaderRoute: typeof AuthenticatedSpecialistNotesRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/specialist/messages': {
      id: '/_authenticated/specialist/messages'
      path: '/messages'
      fullPath: '/specialist/messages'
      preLoaderRoute: typeof AuthenticatedSpecialistMessagesRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/specialist/evaluations': {
      id: '/_authenticated/specialist/evaluations'
      path: '/evaluations'
      fullPath: '/specialist/evaluations'
      preLoaderRoute: typeof AuthenticatedSpecialistEvaluationsRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/specialist/diagnoses': {
      id: '/_authenticated/specialist/diagnoses'
      path: '/diagnoses'
      fullPath: '/specialist/diagnoses'
      preLoaderRoute: typeof AuthenticatedSpecialistDiagnosesRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/specialist/children': {
      id: '/_authenticated/specialist/children'
      path: '/children'
      fullPath: '/specialist/children'
      preLoaderRoute: typeof AuthenticatedSpecialistChildrenRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/specialist/appointments': {
      id: '/_authenticated/specialist/appointments'
      path: '/appointments'
      fullPath: '/specialist/appointments'
      preLoaderRoute: typeof AuthenticatedSpecialistAppointmentsRouteImport
      parentRoute: typeof AuthenticatedSpecialistRouteRoute
    }
    '/_authenticated/parent/progress': {
      id: '/_authenticated/parent/progress'
      path: '/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof AuthenticatedParentProgressRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/parent/messages': {
      id: '/_authenticated/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof AuthenticatedParentMessagesRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/parent/diagnosis': {
      id: '/_authenticated/parent/diagnosis'
      path: '/diagnosis'
      fullPath: '/parent/diagnosis'
      preLoaderRoute: typeof AuthenticatedParentDiagnosisRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/parent/children': {
      id: '/_authenticated/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof AuthenticatedParentChildrenRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/parent/attendance': {
      id: '/_authenticated/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof AuthenticatedParentAttendanceRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/parent/assignments': {
      id: '/_authenticated/parent/assignments'
      path: '/assignments'
      fullPath: '/parent/assignments'
      preLoaderRoute: typeof AuthenticatedParentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/parent/appointments': {
      id: '/_authenticated/parent/appointments'
      path: '/appointments'
      fullPath: '/parent/appointments'
      preLoaderRoute: typeof AuthenticatedParentAppointmentsRouteImport
      parentRoute: typeof AuthenticatedParentRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/statistics': {
      id: '/_authenticated/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AuthenticatedAdminStatisticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/children': {
      id: '/_authenticated/admin/children'
      path: '/children'
      fullPath: '/admin/children'
      preLoaderRoute: typeof AuthenticatedAdminChildrenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/user/$userId': {
      id: '/_authenticated/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUserUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminChildrenRoute: typeof AuthenticatedAdminChildrenRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminStatisticsRoute: typeof AuthenticatedAdminStatisticsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUserUserIdRoute: typeof AuthenticatedAdminUserUserIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
    AuthenticatedAdminChildrenRoute: AuthenticatedAdminChildrenRoute,
    AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
    AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
    AuthenticatedAdminStatisticsRoute: AuthenticatedAdminStatisticsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminUserUserIdRoute: AuthenticatedAdminUserUserIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedParentRouteRouteChildren {
  AuthenticatedParentAppointmentsRoute: typeof AuthenticatedParentAppointmentsRoute
  AuthenticatedParentAssignmentsRoute: typeof AuthenticatedParentAssignmentsRoute
  AuthenticatedParentAttendanceRoute: typeof AuthenticatedParentAttendanceRoute
  AuthenticatedParentChildrenRoute: typeof AuthenticatedParentChildrenRoute
  AuthenticatedParentDiagnosisRoute: typeof AuthenticatedParentDiagnosisRoute
  AuthenticatedParentMessagesRoute: typeof AuthenticatedParentMessagesRoute
  AuthenticatedParentProgressRoute: typeof AuthenticatedParentProgressRoute
  AuthenticatedParentIndexRoute: typeof AuthenticatedParentIndexRoute
}

const AuthenticatedParentRouteRouteChildren: AuthenticatedParentRouteRouteChildren =
  {
    AuthenticatedParentAppointmentsRoute: AuthenticatedParentAppointmentsRoute,
    AuthenticatedParentAssignmentsRoute: AuthenticatedParentAssignmentsRoute,
    AuthenticatedParentAttendanceRoute: AuthenticatedParentAttendanceRoute,
    AuthenticatedParentChildrenRoute: AuthenticatedParentChildrenRoute,
    AuthenticatedParentDiagnosisRoute: AuthenticatedParentDiagnosisRoute,
    AuthenticatedParentMessagesRoute: AuthenticatedParentMessagesRoute,
    AuthenticatedParentProgressRoute: AuthenticatedParentProgressRoute,
    AuthenticatedParentIndexRoute: AuthenticatedParentIndexRoute,
  }

const AuthenticatedParentRouteRouteWithChildren =
  AuthenticatedParentRouteRoute._addFileChildren(
    AuthenticatedParentRouteRouteChildren,
  )

interface AuthenticatedSpecialistRouteRouteChildren {
  AuthenticatedSpecialistAppointmentsRoute: typeof AuthenticatedSpecialistAppointmentsRoute
  AuthenticatedSpecialistChildrenRoute: typeof AuthenticatedSpecialistChildrenRoute
  AuthenticatedSpecialistDiagnosesRoute: typeof AuthenticatedSpecialistDiagnosesRoute
  AuthenticatedSpecialistEvaluationsRoute: typeof AuthenticatedSpecialistEvaluationsRoute
  AuthenticatedSpecialistMessagesRoute: typeof AuthenticatedSpecialistMessagesRoute
  AuthenticatedSpecialistNotesRoute: typeof AuthenticatedSpecialistNotesRoute
  AuthenticatedSpecialistPlansRoute: typeof AuthenticatedSpecialistPlansRoute
  AuthenticatedSpecialistIndexRoute: typeof AuthenticatedSpecialistIndexRoute
}

const AuthenticatedSpecialistRouteRouteChildren: AuthenticatedSpecialistRouteRouteChildren =
  {
    AuthenticatedSpecialistAppointmentsRoute:
      AuthenticatedSpecialistAppointmentsRoute,
    AuthenticatedSpecialistChildrenRoute: AuthenticatedSpecialistChildrenRoute,
    AuthenticatedSpecialistDiagnosesRoute:
      AuthenticatedSpecialistDiagnosesRoute,
    AuthenticatedSpecialistEvaluationsRoute:
      AuthenticatedSpecialistEvaluationsRoute,
    AuthenticatedSpecialistMessagesRoute: AuthenticatedSpecialistMessagesRoute,
    AuthenticatedSpecialistNotesRoute: AuthenticatedSpecialistNotesRoute,
    AuthenticatedSpecialistPlansRoute: AuthenticatedSpecialistPlansRoute,
    AuthenticatedSpecialistIndexRoute: AuthenticatedSpecialistIndexRoute,
  }

const AuthenticatedSpecialistRouteRouteWithChildren =
  AuthenticatedSpecialistRouteRoute._addFileChildren(
    AuthenticatedSpecialistRouteRouteChildren,
  )

interface AuthenticatedTeacherRouteRouteChildren {
  AuthenticatedTeacherAssignmentsRoute: typeof AuthenticatedTeacherAssignmentsRoute
  AuthenticatedTeacherAttendanceRoute: typeof AuthenticatedTeacherAttendanceRoute
  AuthenticatedTeacherChildrenRoute: typeof AuthenticatedTeacherChildrenRoute
  AuthenticatedTeacherGradesRoute: typeof AuthenticatedTeacherGradesRoute
  AuthenticatedTeacherMessagesRoute: typeof AuthenticatedTeacherMessagesRoute
  AuthenticatedTeacherNotesRoute: typeof AuthenticatedTeacherNotesRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
}

const AuthenticatedTeacherRouteRouteChildren: AuthenticatedTeacherRouteRouteChildren =
  {
    AuthenticatedTeacherAssignmentsRoute: AuthenticatedTeacherAssignmentsRoute,
    AuthenticatedTeacherAttendanceRoute: AuthenticatedTeacherAttendanceRoute,
    AuthenticatedTeacherChildrenRoute: AuthenticatedTeacherChildrenRoute,
    AuthenticatedTeacherGradesRoute: AuthenticatedTeacherGradesRoute,
    AuthenticatedTeacherMessagesRoute: AuthenticatedTeacherMessagesRoute,
    AuthenticatedTeacherNotesRoute: AuthenticatedTeacherNotesRoute,
    AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  }

const AuthenticatedTeacherRouteRouteWithChildren =
  AuthenticatedTeacherRouteRoute._addFileChildren(
    AuthenticatedTeacherRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedParentRouteRoute: typeof AuthenticatedParentRouteRouteWithChildren
  AuthenticatedSpecialistRouteRoute: typeof AuthenticatedSpecialistRouteRouteWithChildren
  AuthenticatedTeacherRouteRoute: typeof AuthenticatedTeacherRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedParentRouteRoute: AuthenticatedParentRouteRouteWithChildren,
  AuthenticatedSpecialistRouteRoute:
    AuthenticatedSpecialistRouteRouteWithChildren,
  AuthenticatedTeacherRouteRoute: AuthenticatedTeacherRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
